- eslint-config/index.js
- eslint-config/package.json
I'm not able to add Misha or Danylo to reviewers. Added as warning as Misha has requested. I think it will be a bit easier for students to start. In another config for advanced tasks we'll add this rule as `error`
> added max-len rule as warning

- htmllint-config/.htmllintrc
- htmllint-config/package.json
> added rules to allow '&' and 'viewBox' in attributes

- backstop-config/index.js
- backstop-config/package.json
- backstop-config/readme.md
Change rule.
Upgrade version of the package.
> updated readme, add examples.

- browsersync-config/package.json
- browsersync-config/readme.md
changed readme file and package version
> Browsersync

- backstop-config/index.js
- backstop-config/package.json
I would like to hide full reference URL from tasks. Will use it like this
```
referenceUrl: basicScenario.referenceUrl + '/human-rights/',
```
> Default reference url

- eslint-config/index.js
required line break in blocks after curly braces
in objects it allow write to single line or multiline only
> Whitespace required before return, block-like, declarations

- eslint-config/index.js
- eslint-config/package.json
```
const obj = { line }
```
```
const obj = {
long_line_long_line_long_line_long_line_long_line_long_line,
}
```
^^^
each of above is allowed
> Allow write object body with one line in new line

- eslint-config-internal/index.js
- eslint-config-internal/package.json
- eslint-config-internal/readme.md
added config for internal esling config
> eslint internal config

- eslint-config-internal/index.js
- eslint-config-internal/package.json
- eslint-config-react-internal/package.json
update internal eslint packages
> rules updated

- eslint-config-internal/index.js
- eslint-config-internal/package.json
- eslint-config-react-internal/package.json
> added rule to internal config

- eslint-config/index.js
https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimage.prntscr.com%2Fimage%2FECiAZ6ysRdmG46CURco6-Q.png
> fixed linter error

- mate-scripts/package-lock.json
- mate-scripts/package.json
> updated version, made publish

- eslint-config-internal/index.js
- eslint-config-internal/package-lock.json
- eslint-config-internal/package.json
Added eslint-plugin-ternary
https://www.npmjs.com/package/eslint-plugin-ternary?activeTab=readme
Also added rule 
'multiline-ternary': ['error', 'always']
> Added eslint-plugin-ternary

- eslint-config-react-internal/package.json
- updated @mate-academy/eslint-config-internal to latest version 
- updated the package to 15 version
> [eslint-config-react-internal] update dependancies

- eslint-config-internal/index.js
- eslint-config-internal/package.json
- eslint-config-react-internal/.npmrc
- eslint-config-react-internal/package.json
added no-use-before-define-rule, updated internal packages
> [ESLint]: added no-use-before-define-rule, updated internal packages

- eslint-config-internal/index.js
- eslint-config-internal/package.json
- eslint-config-react-internal/package.json
added 'no-use-before-define': 'off' rule
> added no-use rule

- eslint-config-internal/index.js
- eslint-config-internal/package.json
- eslint-config-react-internal/package.json
> added correct rule usage, changed version

- eslint-config/package.json
Forgot to update the version of package((
> [Student eslint]: Update version

- eslint-config/package.json
And i published package on the wrong branch(
> [Student eslint]: Version updated once again

- mate-scripts/.eslintrc.js
- mate-scripts/README.md
- mate-scripts/package-lock.json
- mate-scripts/package.json
- mate-scripts/src/commands/Test.command.ts
- mate-scripts/src/localScripts/repoNamesFromDb.json
- mate-scripts/src/localScripts/repositories-raw.json
- mate-scripts/src/localScripts/repositoriesData.json
- mate-scripts/src/localScripts/updateRepos/ReposUpdater.ts
- mate-scripts/src/services/Jest.service.ts
- mate-scripts/src/typedefs.ts
> Fix tests in workflow

- mate-scripts/src/localScripts/repositories-raw.json
- mate-scripts/src/localScripts/repositoriesData.json
> [mate-scripts]: added react_lest-of-goods-hooks task to repositories

- matelint/README.md
- matelint/bin/matelint.js
- matelint/lib/config.js
- matelint/lib/defaultConfig.js
- matelint/lib/fs/findConfig.js
- matelint/lib/fs/findHtmlFiles.js
- matelint/lib/fs/shouldIgnoreFile.js
- matelint/lib/lint/Linter.js
- matelint/lib/lint/getRules.js
- matelint/lib/lint/index.js
- matelint/lib/lint/makeChecker.js
- matelint/lib/lint/makeLinter.js
- matelint/lib/lint/parseHtml.js
- matelint/lib/matelint.js
- matelint/lib/printReports/formatError.js
- matelint/lib/printReports/printReports.js
- matelint/lib/rules/closing-and-opening-on-seme-level.js
- matelint/lib/rules/indents-for-attrs.js
- matelint/lib/rules/index.js
- matelint/lib/rules/max-attrs-count-in-line.js
- matelint/package-lock.json
- matelint/package.json
- matelint/rules-description.md
> [MateLint]: Implement matelint

- bemlint/lib/lint/makeGetClasses.js
- bemlint/package-lock.json
- bemlint/package.json
Update-get-classes-logic-for-bemlint
[ClickUp](https://app.clickup.com/t/24383048/LMS-3356)
Before:
Now:
> [Bemlint]: Update-get-classes-logic-for-bemlint

- eslint-config/index.js
> Fix no-prototype-builtins eslint value

- eslint-config-internal/index.js
- eslint-config-internal/package-lock.json
- eslint-config-internal/package.json
Configure multiline function arguments
> [JS]: add rules to eslint according to styleguide

- mate-scripts/package-lock.json
- mate-scripts/package.json
- mate-scripts/src/commands/Test.command.ts
- mate-scripts/src/controllers/lint.controller.ts
- mate-scripts/src/localScripts/redelieverFailedWebHooks/main.ts
- mate-scripts/src/services/Cypress.service.ts
- mate-scripts/src/services/Jest.service.ts
- mate-scripts/src/services/Report.service.ts
- mate-scripts/src/tools/Spinner.ts
- mate-scripts/src/tools/execBashCode.ts
- package-lock.json
This PR resolves the issue where Cypress tests in `layoutDOM` projects were not executed because the server was not running. Additionally, it introduces an improved reporting feature by introducing a new reusable Report service.
- version will be updated and published after review
Before/after demo
https://github.com/mate-academy/fed/assets/54940595/55bf0bf2-3819-4afd-bf1f-b846030e1553
> [LayoutDOM]: fix test command and add reusable report service

- eslint-config-react-typescript/index.js
- eslint-config-react-typescript/package-lock.json
- eslint-config-react-typescript/package.json
added prettier packages, edited index - eslintrc
> Feature/prettier_for_eslint-config-react-typescript 

- eslint-config-react-typescript/index.js
- eslint-config-react-typescript/package-lock.json
- eslint-config-react-typescript/package.json
> Revert "Feature/prettier_for_eslint-config-react-typescript "

- stylelint-config/package-lock.json
- stylelint-config/package.json
Updated stylelint config version
> Updated stylelint config version
